"""update group table info 

Revision ID: 11c85763d681
Revises: ce3e0b822160
Create Date: 2023-03-29 14:45:12.157183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c85763d681'
down_revision = 'ce3e0b822160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('im_group', sa.Column('status', sa.SMALLINT(), nullable=True, comment='群状态:0正常 1解散'))
    op.drop_column('im_group', 'statues')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('im_group', sa.Column('statues', sa.SMALLINT(), autoincrement=False, nullable=True, comment='群状态:0正常 1解散'))
    op.drop_column('im_group', 'status')
    # ### end Alembic commands ###
