"""table friend manager add column refuse reason

Revision ID: 42dc03af605b
Revises: 9a734837994c
Create Date: 2023-03-24 09:49:07.426361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dc03af605b'
down_revision = '9a734837994c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('im_friend_manager_record', sa.Column('refuse_reason', sa.TEXT(), nullable=True, comment='拒绝通过理由'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('im_friend_manager_record', 'refuse_reason')
    # ### end Alembic commands ###
