"""add table2

Revision ID: a0f2be203e73
Revises: f85be614a8a9
Create Date: 2023-03-17 15:19:04.590982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f2be203e73'
down_revision = 'f85be614a8a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=256), nullable=False, comment='用户账号密码'),
    sa.Column('email', sa.String(length=256), nullable=False, comment='账号邮箱'),
    sa.Column('telephone', sa.String(length=256), nullable=True, comment='用户电话'),
    sa.Column('avatar', sa.String(length=256), nullable=True, comment='用户头像'),
    sa.Column('age', sa.SMALLINT(), nullable=True, comment='用户年龄'),
    sa.Column('sex', sa.SMALLINT(), nullable=True, comment='用户性别'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('im_group',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('group_name', sa.String(length=256), nullable=False, comment='群聊名称'),
    sa.Column('creator_id', sa.BIGINT(), nullable=True, comment='创建者'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.BIGINT(), nullable=True, comment='群主'),
    sa.Column('announcement', sa.TEXT(), nullable=True, comment='群公告'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['im_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['im_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('im_message',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('msg_from', sa.BIGINT(), nullable=True),
    sa.Column('msg_to', sa.BIGINT(), nullable=True),
    sa.Column('msg_content', sa.TEXT(), nullable=True, comment='消息内容'),
    sa.Column('msg_type', sa.SMALLINT(), nullable=True, comment='消息类型'),
    sa.Column('send_time', sa.DateTime(timezone=True), nullable=True, comment='发送时间'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['msg_from'], ['im_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['msg_to'], ['im_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('im_user_friends_ship',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True, comment='用户ID'),
    sa.Column('friend_id', sa.BIGINT(), nullable=True, comment='好友ID'),
    sa.Column('friend_group', sa.String(length=256), nullable=True),
    sa.Column('current_contact_time', sa.DateTime(timezone=True), nullable=True, comment='最近联系时间'),
    sa.Column('friend_nickname', sa.String(length=256), nullable=False, comment='好友昵称'),
    sa.Column('relationship', sa.SMALLINT(), nullable=False, comment='好友关系(1:好友 2:陌生人)'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['im_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['im_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('im_user_group_ship',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True, comment='用户ID'),
    sa.Column('group_id', sa.BIGINT(), nullable=True, comment='群ID'),
    sa.Column('current_contact_time', sa.DateTime(timezone=True), nullable=True, comment='最近更新时间'),
    sa.Column('group_nickname', sa.String(length=256), nullable=False, comment='群昵称'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['im_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['im_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im_user_group_ship')
    op.drop_table('im_user_friends_ship')
    op.drop_table('im_message')
    op.drop_table('im_group')
    op.drop_table('im_user')
    # ### end Alembic commands ###
