"""update group table info 

Revision ID: ce3e0b822160
Revises: bc266557985c
Create Date: 2023-03-28 16:06:29.143158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3e0b822160'
down_revision = 'bc266557985c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('im_group', sa.Column('member_count', sa.SMALLINT(), nullable=False, comment='群成员人数',server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('im_group', 'member_count')
    # ### end Alembic commands ###
