"""add friend messgae record

Revision ID: d30c0acf8af4
Revises: ac695912d9a2
Create Date: 2023-03-22 22:20:02.638926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd30c0acf8af4'
down_revision = 'ac695912d9a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_friend_manager_record',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('msg_from', sa.BIGINT(), nullable=True),
    sa.Column('msg_to', sa.BIGINT(), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True, comment='发送时间'),
    sa.Column('deal_time', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('accept', sa.Boolean(), nullable=False, comment='是否通过'),
    sa.Column('check_info', sa.TEXT(), nullable=True, comment='验证消息描述'),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['msg_from'], ['im_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['msg_to'], ['im_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('im_friend_manager_record')
    # ### end Alembic commands ###
