"""add table

Revision ID: f85be614a8a9
Revises: 393c2b21890d
Create Date: 2023-03-17 14:52:18.549007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85be614a8a9'
down_revision = '393c2b21890d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
